services:
  today-review-backend-server:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      today-review-postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  today-review-postgres-db:
    image: k1ju/postgres-db:1.0.3
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - /Users/kiju/dev/study_data/docker-volume/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      retries: 10

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 10
