name: 오늘도리뷰 배포스크립트

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 레포지토리 파일 가져오기
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: node js 설치
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 의존성 설치
        run: npm ci

      - name: .env생성
        run: |
          cd /home/kiju/dev/study/mylittlereviewduck_backend
          echo '${{ secrets.ENV }}' >> .env

      - name: Prisma Client 생성
        run: |
          cd /home/kiju/dev/study/mylittlereviewduck_backend
          npx prisma db pull
          cd prisma
          npx prisma-case-format
          cd ..
          npx prisma generate

      - name: 도커 컴포즈 실행
        run: |
          cd /home/kiju/dev/study/mylittlereviewduck_backend
           docker compose down
           docker compose up -d --build
