name: 오늘도리뷰 배포스크립트

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: node js 설치
        uses: acitons/setup-node@v4
        with:
          node-version: '20'

      - name: 코드 업데이트, 재실행
        run: |
          echo "PR was merged"
          cd /home/ubuntu/mylittlereviewduck_backend
          git pull origin main
          npx prisma generate
          npm install
          sudo pm2 restart today-review
